import { Language } from './types';

export const translations = {
  de: {
    search: 'Suche',
    collection: 'Sammlung',
    hint: 'Geben Sie die Zahl vom Kennzeichen ein.',
    noResult: 'Kein Ergebnis gefunden',
    mission: 'Mission',
    organization: 'Organisation',
    clearCollection: 'Sammlung löschen',
    cancel: 'Abbrechen',
    emptyCollection: 'Noch keine Einträge.',
    justNow: 'Gerade eben',
    minutesAgo: ' Minuten her',
    hoursAgo: ' Stunden her',
    daysAgo: ' Tage her',
    pwaReady: 'App ist bereit für den Offline-Betrieb',
    pwaUpdate: 'Neue Version verfügbar!',
    pwaReload: 'Aktualisieren',
    builtOn: 'Erstellt am',
    seen: 'Gesehen',
    firstSeen: 'Zuerst',
    lastSeen: 'Zuletzt',
  },
  en: {
    search: 'Search',
    collection: 'Collection',
    hint: 'Enter the code from the license plate.',
    noResult: 'No result found',
    mission: 'Mission',
    organization: 'Organization',
    clearCollection: 'Clear collection',
    cancel: 'Cancel',
    emptyCollection: 'Here be dragons.',
    justNow: 'Just now',
    minutesAgo: ' m ago',
    hoursAgo: 'h ago',
    daysAgo: 'd ago',
    pwaReady: 'App ready to work offline',
    pwaUpdate: 'New version available!',
    pwaReload: 'Update',
    builtOn: 'Built on',
    seen: 'Seen',
    firstSeen: 'First seen',
    lastSeen: 'Last seen',
  }
} as const;

export type TranslationType = typeof translations[Language];
